### ISSUE TITLE
404 on jQuery file

### ISSUE THREAD

**Issue by dav1170** [YAMJ/skins#1]
Hello,

When loading interface in a case sensitive environnemnt, skin doesn't load because JQuery is not found.
(js/jquery.js file).

sed "s|js/jQuery.js|js/jquery.js|g" -i *.html has fixed this issue.

**Comment by jluc2808** [comment]
very strange , because my local github storage , contains jQuery (with Q not q) and the repository on github is with jquery 
when i look at the storage place build to store and upload from www.reflexequilibre.fr/download/bikini v3.0.8.zip i get the jQuery too (in js folder) 

my recommandation is don't use directly the github (download zip) but it's better to get and use the url referenced in the bikini thread http://www.networkedmediatank.com/showthread.php?tid=69504

**Comment by dav1170** [comment]
I'm sorry, but this issue cannot be closed: many users - like me - will try to get the latest version from github when available.
So you can't say that we must use a different way of set up if you use your github repository in your set up links.

my problem is not that we cannot find the js/jQuery.js file, my problem is that the source code try to find jQuery.js file when only the js/jquery.js file is available.

regards
